apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: cs3219.azurecr.io/gateway
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: peerprep-config
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching
  template:
    metadata:
      labels:
        app: matching
    spec:
      containers:
        - name: matching
          image: cs3219.azurecr.io/matching
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: peerprep-config
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: cs3219.azurecr.io/user
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: peerprep-config
          env:
            - name: DB_CLOUD_URI
              value: 'mongodb+srv://cs3219-g15:cs3219-g15@cs3219-g15.ryvsrmt.mongodb.net/?retryWrites=true&w=majority'
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coding
  template:
    metadata:
      labels:
        app: coding
    spec:
      containers:
        - name: coding
          image: cs3219.azurecr.io/coding
          imagePullPolicy: Always
          ports:
            - containerPort: 8002
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: peerprep-config
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: question
spec:
  replicas: 1
  selector:
    matchLabels:
      app: question
  template:
    metadata:
      labels:
        app: question
    spec:
      containers:
        - name: question
          image: cs3219.azurecr.io/question
          imagePullPolicy: Always
          ports:
            - containerPort: 8004
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: peerprep-config
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: history
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history
  template:
    metadata:
      labels:
        app: history
    spec:
      containers:
        - name: history
          image: cs3219.azurecr.io/history
          imagePullPolicy: Always
          ports:
            - containerPort: 8005
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: peerprep-config
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video
  template:
    metadata:
      labels:
        app: video
    spec:
      containers:
        - name: video
          image: cs3219.azurecr.io/video
          imagePullPolicy: Always
          ports:
            - containerPort: 8003
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: peerprep-config
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: room
spec:
  replicas: 1
  selector:
    matchLabels:
      app: room
  template:
    metadata:
      labels:
        app: room
    spec:
      containers:
        - name: room
          image: cs3219.azurecr.io/room
          imagePullPolicy: Always
          ports:
            - containerPort: 8006
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
          envFrom:
            - configMapRef:
                name: peerprep-config
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: cs3219.azurecr.io/judge0/judge0:cs3219
          imagePullPolicy: Always
          ports:
            - containerPort: 2358
          privileged: true
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workers
  template:
    metadata:
      labels:
        app: workers
    spec:
      containers:
        - name: workers
          image: cs3219.azurecr.io/judge0/judge0:cs3219
          imagePullPolicy: Always
          command: ['./scripts/workers']
          privileged: true
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
      imagePullSecrets:
        - name: azureregistrykey
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: cs3219.azurecr.io/postgres:cs3219
          imagePullPolicy: Always
          ports:
            - containerPort: 2358
          privileged: true
          resources:
            limits:
              memory: 512Mi
              cpu: '250m'
            requests:
              memory: 256Mi
              cpu: '250m'
      imagePullSecrets:
        - name: azureregistrykey
---

